name: Testing & Linting

on: [push]

jobs:
  Cool-Test:
    runs-on: ubuntu-latest
    steps:

    - name: Get Node Version 14
       uses: actions/setup-node@v2-beta
       with:
         node-version: '14'

     - name: Installing dependencies
       run: npm ci

     - name: Running tests
       run: npm run test
